/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    documents: Document;
    flights: Flight;
    notices: Notice;
    pages: Page;
    faqs: Faq;
    airlines: Airline;
    'news-events': NewsEvent;
    'airport-project': AirportProject;
    careers: Career;
    'page-views': PageView;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    flights: FlightsSelect<false> | FlightsSelect<true>;
    notices: NoticesSelect<false> | NoticesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    airlines: AirlinesSelect<false> | AirlinesSelect<true>;
    'news-events': NewsEventsSelect<false> | NewsEventsSelect<true>;
    'airport-project': AirportProjectSelect<false> | AirportProjectSelect<true>;
    careers: CareersSelect<false> | CareersSelect<true>;
    'page-views': PageViewsSelect<false> | PageViewsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'fr' | 'mfe') | ('en' | 'fr' | 'mfe')[];
  globals: {
    'site-settings': SiteSetting;
    'home-page': HomePage;
    'passenger-guide': PassengerGuide;
    'transport-parking': TransportParking;
    'accessibility-info': AccessibilityInfo;
    'airport-map': AirportMap;
    'contact-info': ContactInfo;
    regulations: Regulation;
    'usage-fees': UsageFee;
    'vip-lounge': VipLounge;
    'emergency-services': EmergencyService;
    'working-hours-directions': WorkingHoursDirection;
    'useful-links': UsefulLink;
    'management-staff': ManagementStaff;
    'legal-pages': LegalPage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'passenger-guide': PassengerGuideSelect<false> | PassengerGuideSelect<true>;
    'transport-parking': TransportParkingSelect<false> | TransportParkingSelect<true>;
    'accessibility-info': AccessibilityInfoSelect<false> | AccessibilityInfoSelect<true>;
    'airport-map': AirportMapSelect<false> | AirportMapSelect<true>;
    'contact-info': ContactInfoSelect<false> | ContactInfoSelect<true>;
    regulations: RegulationsSelect<false> | RegulationsSelect<true>;
    'usage-fees': UsageFeesSelect<false> | UsageFeesSelect<true>;
    'vip-lounge': VipLoungeSelect<false> | VipLoungeSelect<true>;
    'emergency-services': EmergencyServicesSelect<false> | EmergencyServicesSelect<true>;
    'working-hours-directions': WorkingHoursDirectionsSelect<false> | WorkingHoursDirectionsSelect<true>;
    'useful-links': UsefulLinksSelect<false> | UsefulLinksSelect<true>;
    'management-staff': ManagementStaffSelect<false> | ManagementStaffSelect<true>;
    'legal-pages': LegalPagesSelect<false> | LegalPagesSelect<true>;
  };
  locale: 'en' | 'fr' | 'mfe';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  fullName: string;
  roles: ('super_admin' | 'content_admin' | 'approver' | 'operations_editor' | 'translator' | 'viewer_auditor')[];
  /**
   * Preferred dashboard language.
   */
  preferredLocale?: ('en' | 'fr' | 'mfe') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Images uploaded here are stored in the Supabase public media bucket and served via CDN. Placement on the public site is controlled by explicit image fields elsewhere in the CMS.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Required for accessibility and SEO. Describe the image content concisely.
   */
  alt: string;
  caption?: string | null;
  /**
   * Used only to organise media in the CMS. Frontend placement is controlled by explicit upload fields on pages, news items, airlines, and other content types.
   */
  mediaCategory?: ('hero' | 'page' | 'airline' | 'staff' | 'news' | 'amenity' | 'map' | 'general') | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Protected PDFs stored in the private Supabase bucket. Access requires server-generated signed URLs.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  title: string;
  /**
   * Brief description of what this document contains.
   */
  description?: string | null;
  /**
   * Controls the storage prefix and determines who can access this document.
   */
  documentType: 'communique' | 'guidance' | 'regulation' | 'fee_schedule' | 'general';
  /**
   * Restricted documents are readable only by their uploader unless the user is a super admin.
   */
  visibility: 'public' | 'internal' | 'restricted';
  /**
   * The date this document comes into effect (optional).
   */
  effectiveDate?: string | null;
  /**
   * Leave blank if this document does not expire.
   */
  expiryDate?: string | null;
  /**
   * Inactive documents are hidden from the frontend but retained for audit purposes.
   */
  isActive?: boolean | null;
  uploadedAt?: string | null;
  uploadedBy?: (number | null) | User;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Manual flight entries. Use this to add flights missing from the AirLabs feed or to override incorrect API data. Entries matching an API flight number will replace the API version.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "flights".
 */
export interface Flight {
  id: number;
  boardType: 'arrival' | 'departure';
  status: 'active' | 'hidden';
  /**
   * Airline code using 2 to 3 uppercase letters or digits (e.g. MK).
   */
  airline: string;
  /**
   * Full flight number. If this matches an API flight, the manual entry takes priority.
   */
  flightNumber: string;
  /**
   * Origin IATA code for arrivals, destination IATA code for departures.
   */
  route: string;
  /**
   * Scheduled arrival/departure time.
   */
  scheduledTime: string;
  /**
   * Leave blank if on time. Set to show a delay or early arrival.
   */
  estimatedTime?: string | null;
  remarks:
    | 'Scheduled'
    | 'On Time'
    | 'Delayed'
    | 'Cancelled'
    | 'Departed'
    | 'En Route'
    | 'Landed'
    | 'Diverted'
    | 'Boarding';
  /**
   * How this entry was created.
   */
  source: 'manual' | 'override';
  updatedAt: string;
  createdAt: string;
}
/**
 * Airport notices, alerts, and announcements.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notices".
 */
export interface Notice {
  id: number;
  /**
   * Short, clear title shown to passengers.
   */
  title: string;
  /**
   * Auto-generated from title if left blank. You can override with a custom slug.
   */
  slug: string;
  /**
   * One or two sentences shown in notice listings and push notifications.
   */
  summary: string;
  /**
   * Full notice body shown on the detail page.
   */
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  category: 'operational' | 'passenger_info' | 'regulation' | 'fee' | 'emergency' | 'corporate';
  status: 'draft' | 'in_review' | 'approved' | 'published' | 'expired' | 'archived';
  /**
   * Leave blank to auto-set when status is changed to Published.
   */
  publishedAt?: string | null;
  /**
   * Optional. Notice will be marked Expired after this date.
   */
  expiresAt?: string | null;
  /**
   * Highlights this notice with a warning indicator.
   */
  urgent?: boolean | null;
  /**
   * Keeps this notice at the top of listings.
   */
  pinned?: boolean | null;
  /**
   * Surface in the site-wide alert banner (urgent + published only).
   */
  promoteToBanner?: boolean | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  /**
   * Optional images attached to this notice.
   */
  attachments?: (number | Media)[] | null;
  /**
   * Auto-populated when status is set to Approved.
   */
  lastApprovedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Auto-generated from title if left blank. Used in the URL: /[slug]
   */
  slug: string;
  summary: string;
  /**
   * Optional image displayed near the top of this page on the public site.
   */
  pageImage?: (number | null) | Media;
  status: 'draft' | 'in_review' | 'published';
  sections?:
    | {
        heading: string;
        /**
         * Keep section body content to 5000 characters or fewer.
         */
        body: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        bullets?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  /**
   * Write the question as a passenger would ask it.
   */
  question: string;
  /**
   * Clear, concise answer. Keep it under 200 words.
   */
  answer: string;
  category: 'general' | 'flights' | 'transport' | 'accessibility' | 'documents';
  status?: ('draft' | 'published') | null;
  /**
   * Lower = shown first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Airlines operating at Rodrigues / Plaine Corail Airport.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "airlines".
 */
export interface Airline {
  id: number;
  /**
   * Uncheck if this airline has suspended operations.
   */
  isActive?: boolean | null;
  /**
   * Lower number = displayed first.
   */
  displayOrder?: number | null;
  name: string;
  /**
   * Two-letter designator (e.g. MK for Air Mauritius).
   */
  iataCode: string;
  icaoCode?: string | null;
  /**
   * PNG/SVG with transparent background preferred.
   */
  logo?: (number | null) | Media;
  description?: string | null;
  /**
   * Full URL starting with http:// or https://
   */
  website?: string | null;
  contactPhone?: string | null;
  destinations?:
    | {
        city: string;
        airportCode?: string | null;
        country?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Airport news articles and event announcements.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-events".
 */
export interface NewsEvent {
  id: number;
  title: string;
  /**
   * Auto-generated from title if left blank. Used in the URL: /news-events/[slug]
   */
  slug: string;
  type: 'news' | 'event' | 'press' | 'announcement';
  /**
   * Short summary for listing pages and meta description (160 chars recommended).
   */
  summary: string;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Shown on the public news listing and the individual article page.
   */
  featuredImage?: (number | null) | Media;
  eventDetails?: {
    startDate?: string | null;
    endDate?: string | null;
    location?: string | null;
  };
  status?: ('draft' | 'in_review' | 'published' | 'archived') | null;
  publishedAt?: string | null;
  /**
   * Auto-populated when an approver publishes from In Review.
   */
  lastApprovedBy?: (number | null) | User;
  isPinned?: boolean | null;
  /**
   * Downloadable documents displayed as links on the news item.
   */
  attachments?:
    | {
        label: string;
        file: number | Document;
        id?: string | null;
      }[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Airport project updates, tender documents, and press releases.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "airport-project".
 */
export interface AirportProject {
  id: number;
  title: string;
  /**
   * Auto-generated from title if left blank. Used in the URL: /airport-project/[slug]
   */
  slug: string;
  category: 'notice_to_bidders' | 'press_release' | 'site_visit' | 'environmental' | 'general';
  /**
   * Description shown on the listing page.
   */
  summary: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Thumbnail shown on the listing page.
   */
  featuredImage?: (number | null) | Media;
  /**
   * Downloadable files (PDFs, tender documents, photos, etc.).
   */
  attachments?:
    | {
        label: string;
        file: number | Document;
        id?: string | null;
      }[]
    | null;
  status?: ('draft' | 'in_review' | 'published' | 'archived') | null;
  publishedAt?: string | null;
  /**
   * Auto-populated when an approver publishes from In Review.
   */
  lastApprovedBy?: (number | null) | User;
  isPinned?: boolean | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Career opportunities and vacancy notices with downloadable PDF documents.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers".
 */
export interface Career {
  id: number;
  title: string;
  /**
   * Auto-generated from title if left blank. Used as a stable career notice identifier.
   */
  slug: string;
  /**
   * Description shown on the public Career listing page.
   */
  summary: string;
  /**
   * Upload the official vacancy PDF through the Documents collection.
   */
  attachments: {
    label: string;
    file: number | Document;
    id?: string | null;
  }[];
  status?: ('draft' | 'in_review' | 'published' | 'archived') | null;
  publishedAt?: string | null;
  /**
   * Auto-populated when an approver publishes from In Review.
   */
  lastApprovedBy?: (number | null) | User;
  isPinned?: boolean | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Anonymized page view events for internal analytics. Events are retained for 90 days.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-views".
 */
export interface PageView {
  id: number;
  /**
   * URL path (e.g. /arrivals)
   */
  path: string;
  /**
   * Referrer domain (e.g. google.com)
   */
  referrer?: string | null;
  /**
   * Locale inferred from the tracked URL path.
   */
  locale?: ('en' | 'fr' | 'mfe') | null;
  device?: ('desktop' | 'mobile' | 'tablet') | null;
  /**
   * Browser accept-language (first tag, e.g. en)
   */
  language?: string | null;
  /**
   * Daily anonymized visitor hash (SHA-256 of IP + date). Not reversible.
   */
  visitorHash?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'flights';
        value: number | Flight;
      } | null)
    | ({
        relationTo: 'notices';
        value: number | Notice;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'airlines';
        value: number | Airline;
      } | null)
    | ({
        relationTo: 'news-events';
        value: number | NewsEvent;
      } | null)
    | ({
        relationTo: 'airport-project';
        value: number | AirportProject;
      } | null)
    | ({
        relationTo: 'careers';
        value: number | Career;
      } | null)
    | ({
        relationTo: 'page-views';
        value: number | PageView;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  fullName?: T;
  roles?: T;
  preferredLocale?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  mediaCategory?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  documentType?: T;
  visibility?: T;
  effectiveDate?: T;
  expiryDate?: T;
  isActive?: T;
  uploadedAt?: T;
  uploadedBy?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "flights_select".
 */
export interface FlightsSelect<T extends boolean = true> {
  boardType?: T;
  status?: T;
  airline?: T;
  flightNumber?: T;
  route?: T;
  scheduledTime?: T;
  estimatedTime?: T;
  remarks?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notices_select".
 */
export interface NoticesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  body?: T;
  category?: T;
  status?: T;
  publishedAt?: T;
  expiresAt?: T;
  urgent?: T;
  pinned?: T;
  promoteToBanner?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  attachments?: T;
  lastApprovedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  pageImage?: T;
  status?: T;
  sections?:
    | T
    | {
        heading?: T;
        body?: T;
        bullets?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  status?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "airlines_select".
 */
export interface AirlinesSelect<T extends boolean = true> {
  isActive?: T;
  displayOrder?: T;
  name?: T;
  iataCode?: T;
  icaoCode?: T;
  logo?: T;
  description?: T;
  website?: T;
  contactPhone?: T;
  destinations?:
    | T
    | {
        city?: T;
        airportCode?: T;
        country?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-events_select".
 */
export interface NewsEventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  type?: T;
  summary?: T;
  body?: T;
  featuredImage?: T;
  eventDetails?:
    | T
    | {
        startDate?: T;
        endDate?: T;
        location?: T;
      };
  status?: T;
  publishedAt?: T;
  lastApprovedBy?: T;
  isPinned?: T;
  attachments?:
    | T
    | {
        label?: T;
        file?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "airport-project_select".
 */
export interface AirportProjectSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  summary?: T;
  body?: T;
  featuredImage?: T;
  attachments?:
    | T
    | {
        label?: T;
        file?: T;
        id?: T;
      };
  status?: T;
  publishedAt?: T;
  lastApprovedBy?: T;
  isPinned?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers_select".
 */
export interface CareersSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  attachments?:
    | T
    | {
        label?: T;
        file?: T;
        id?: T;
      };
  status?: T;
  publishedAt?: T;
  lastApprovedBy?: T;
  isPinned?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-views_select".
 */
export interface PageViewsSelect<T extends boolean = true> {
  path?: T;
  referrer?: T;
  locale?: T;
  device?: T;
  language?: T;
  visitorHash?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Global site identity: name, contact details, social links, and default SEO metadata.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  airportName: string;
  tagline?: string | null;
  primaryPhone?: string | null;
  primaryEmail?: string | null;
  physicalAddress?: string | null;
  workingHours?: string | null;
  socialLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  usefulLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  seoDefaultTitle?: string | null;
  seoDefaultDescription?: string | null;
  /**
   * Fallback image used for social sharing when a page has no featured image. Recommended size: 1200x630.
   */
  defaultOgImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Controls the hero section, service previews, and emergency alert area on the public homepage.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  heroTitle: string;
  heroSummary: string;
  servicesPreview?:
    | {
        title: string;
        summary: string;
        id?: string | null;
      }[]
    | null;
  emergencyAlertTitle?: string | null;
  emergencyAlertBody?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Check-in, baggage, security, and travel preparation guidance displayed on the Passenger Guide page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "passenger-guide".
 */
export interface PassengerGuide {
  id: number;
  introTitle: string;
  introSummary: string;
  sections?:
    | {
        heading: string;
        /**
         * Keep section body content to 5000 characters or fewer.
         */
        body: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        bullets?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  importantContacts?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Transport options, parking, and direction information for the Transport & Parking page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transport-parking".
 */
export interface TransportParking {
  id: number;
  introTitle: string;
  introSummary: string;
  sections?:
    | {
        heading: string;
        /**
         * Keep section body content to 5000 characters or fewer.
         */
        body: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        bullets?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  mapEmbedURL?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Accessibility support details, reduced mobility assistance, and accessible facilities information.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accessibility-info".
 */
export interface AccessibilityInfo {
  id: number;
  introTitle: string;
  introSummary: string;
  sections?:
    | {
        heading: string;
        /**
         * Keep section body content to 5000 characters or fewer.
         */
        body: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        bullets?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  assistanceContact?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Terminal map, embed URL, and key points of interest displayed on the Airport Map page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "airport-map".
 */
export interface AirportMap {
  id: number;
  introTitle: string;
  introSummary: string;
  mapEmbedURL?: string | null;
  points?:
    | {
        name: string;
        category: 'terminal' | 'parking' | 'transport' | 'accessibility' | 'security' | 'services';
        description: string;
        /**
         * Latitude (decimal degrees)
         */
        lat?: number | null;
        /**
         * Longitude (decimal degrees)
         */
        lng?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Help desk contact cards and general enquiry details shown on the Contact page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-info".
 */
export interface ContactInfo {
  id: number;
  helpDeskTitle: string;
  helpDeskSummary: string;
  cards?:
    | {
        title: string;
        value: string;
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Airport rules, conditions of entry, and regulatory notices. Links to official regulation PDFs.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regulations".
 */
export interface Regulation {
  id: number;
  pageTitle: string;
  introduction?: string | null;
  sections?:
    | {
        heading: string;
        body?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        /**
         * Optionally link the official regulation PDF (stored in protected docs bucket).
         */
        attachedDocument?: (number | null) | Document;
        id?: string | null;
      }[]
    | null;
  /**
   * The date these regulations were last reviewed by airport authority.
   */
  lastReviewedDate?: string | null;
  /**
   * Optional disclaimer text shown at the bottom of the regulations page.
   */
  legalDisclaimer?: string | null;
  /**
   * Optional note to include in the approval history when publishing.
   */
  approvalNotes?: string | null;
  approvalHistory?:
    | {
        approvedBy?: (number | null) | User;
        approvedAt?: string | null;
        notes?: string | null;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Airport usage charges, fee categories, and links to approved fee schedule PDFs.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usage-fees".
 */
export interface UsageFee {
  id: number;
  pageTitle: string;
  /**
   * General introduction to the fee structure. Do not include specific amounts without linking the official schedule.
   */
  introduction?: string | null;
  feeCategories?:
    | {
        categoryName: string;
        description?: string | null;
        /**
         * e.g. "Refer to the official fee schedule for current rates."
         */
        noteOnSource?: string | null;
        /**
         * Link the approved fee schedule PDF from the protected docs bucket.
         */
        officialSchedulePDF?: (number | null) | Document;
        effectiveFrom?: string | null;
        id?: string | null;
      }[]
    | null;
  paymentMethods?: string | null;
  contactForEnquiries?: {
    name?: string | null;
    phone?: string | null;
    email?: string | null;
  };
  /**
   * Date fee information was last reviewed and approved by management.
   */
  lastApprovedDate?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * VIP lounge amenities, eligibility, booking details, and operating hours.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vip-lounge".
 */
export interface VipLounge {
  id: number;
  pageTitle: string;
  introduction?: string | null;
  amenities?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  eligibility?: string | null;
  bookingInformation?: string | null;
  operatingHours?: string | null;
  contactPhone?: string | null;
  contactEmail?: string | null;
  loungeImages?:
    | {
        /**
         * Displayed in the public VIP Lounge gallery.
         */
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * CRITICAL: All emergency numbers must be verified before publishing.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "emergency-services".
 */
export interface EmergencyService {
  id: number;
  /**
   * Only approvers and admins may transition emergency contacts to Published.
   */
  status: 'draft' | 'pending_review' | 'published';
  pageTitle: string;
  introduction?: string | null;
  /**
   * The single most important emergency contact (e.g. 999). Displayed prominently.
   */
  primaryEmergencyNumber: string;
  serviceContacts?:
    | {
        serviceName: string;
        phone: string;
        description?: string | null;
        available24h?: boolean | null;
        id?: string | null;
      }[]
    | null;
  medicalFacilities?: string | null;
  /**
   * High-level passenger guidance only. Detailed operational procedures are internal.
   */
  evacuationProcedures?: string | null;
  /**
   * Date emergency contacts were last verified with the airport authority.
   */
  lastVerifiedDate: string;
  /**
   * Name/role of the person who verified these contacts.
   */
  verifiedBy: string;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Airport operating hours, department schedules, location, and directions for getting here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "working-hours-directions".
 */
export interface WorkingHoursDirection {
  id: number;
  pageTitle: string;
  opHours?: {
    /**
     * General operating hours. Note any seasonal variations.
     */
    description?: string | null;
    schedule?:
      | {
          dayOrPeriod: string;
          hours: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Hours for check-in, customs, cargo, etc. if they differ from airport hours.
   */
  departmentHours?:
    | {
        department: string;
        hours: string;
        notes?: string | null;
        id?: string | null;
      }[]
    | null;
  location: {
    address: string;
    /**
     * Full Google Maps URL for the airport location.
     */
    googleMapsURL?: string | null;
    /**
     * Google Maps or OpenStreetMap embed src URL for the iframe.
     */
    mapEmbedURL?: string | null;
    coordinates?: {
      latitude?: number | null;
      longitude?: number | null;
    };
  };
  gettingHere?:
    | {
        transportMode: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Curated external links grouped by category, displayed on the Useful Links page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "useful-links".
 */
export interface UsefulLink {
  id: number;
  pageTitle: string;
  introduction?: string | null;
  linkGroups?:
    | {
        groupName: string;
        links?:
          | {
              label: string;
              /**
               * Full URL including https://
               */
              url: string;
              description?: string | null;
              openInNewTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Airport management team profiles, biographies, and departmental overview.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "management-staff".
 */
export interface ManagementStaff {
  id: number;
  pageTitle: string;
  introduction?: string | null;
  managementTeam?:
    | {
        name: string;
        title: string;
        photo?: (number | null) | Media;
        bio?: string | null;
        department?: string | null;
        displayOrder?: number | null;
        /**
         * Uncheck to hide this person without deleting their record.
         */
        isVisible?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional organisational overview by department.
   */
  departments?:
    | {
        departmentName: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Disclaimer, Terms of Use, and Privacy Policy. Changes require Approver access.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages".
 */
export interface LegalPage {
  id: number;
  disclaimer: {
    title: string;
    content: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    lastUpdated?: string | null;
  };
  termsOfUse: {
    title: string;
    content: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    lastUpdated?: string | null;
    effectiveDate?: string | null;
  };
  privacyPolicy: {
    title: string;
    /**
     * Must comply with applicable data protection legislation (e.g. Mauritius Data Protection Act 2017).
     */
    content: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    lastUpdated?: string | null;
    dataControllerName?: string | null;
    dataControllerEmail?: string | null;
  };
  cookiePolicy?: {
    title?: string | null;
    content?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    lastUpdated?: string | null;
  };
  /**
   * Optional note to include in the approval history when publishing.
   */
  approvalNotes?: string | null;
  approvalHistory?:
    | {
        approvedBy?: (number | null) | User;
        approvedAt?: string | null;
        notes?: string | null;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  airportName?: T;
  tagline?: T;
  primaryPhone?: T;
  primaryEmail?: T;
  physicalAddress?: T;
  workingHours?: T;
  socialLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  usefulLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  seoDefaultTitle?: T;
  seoDefaultDescription?: T;
  defaultOgImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  heroTitle?: T;
  heroSummary?: T;
  servicesPreview?:
    | T
    | {
        title?: T;
        summary?: T;
        id?: T;
      };
  emergencyAlertTitle?: T;
  emergencyAlertBody?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "passenger-guide_select".
 */
export interface PassengerGuideSelect<T extends boolean = true> {
  introTitle?: T;
  introSummary?: T;
  sections?:
    | T
    | {
        heading?: T;
        body?: T;
        bullets?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  importantContacts?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transport-parking_select".
 */
export interface TransportParkingSelect<T extends boolean = true> {
  introTitle?: T;
  introSummary?: T;
  sections?:
    | T
    | {
        heading?: T;
        body?: T;
        bullets?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  mapEmbedURL?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accessibility-info_select".
 */
export interface AccessibilityInfoSelect<T extends boolean = true> {
  introTitle?: T;
  introSummary?: T;
  sections?:
    | T
    | {
        heading?: T;
        body?: T;
        bullets?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  assistanceContact?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "airport-map_select".
 */
export interface AirportMapSelect<T extends boolean = true> {
  introTitle?: T;
  introSummary?: T;
  mapEmbedURL?: T;
  points?:
    | T
    | {
        name?: T;
        category?: T;
        description?: T;
        lat?: T;
        lng?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-info_select".
 */
export interface ContactInfoSelect<T extends boolean = true> {
  helpDeskTitle?: T;
  helpDeskSummary?: T;
  cards?:
    | T
    | {
        title?: T;
        value?: T;
        link?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regulations_select".
 */
export interface RegulationsSelect<T extends boolean = true> {
  pageTitle?: T;
  introduction?: T;
  sections?:
    | T
    | {
        heading?: T;
        body?: T;
        attachedDocument?: T;
        id?: T;
      };
  lastReviewedDate?: T;
  legalDisclaimer?: T;
  approvalNotes?: T;
  approvalHistory?:
    | T
    | {
        approvedBy?: T;
        approvedAt?: T;
        notes?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usage-fees_select".
 */
export interface UsageFeesSelect<T extends boolean = true> {
  pageTitle?: T;
  introduction?: T;
  feeCategories?:
    | T
    | {
        categoryName?: T;
        description?: T;
        noteOnSource?: T;
        officialSchedulePDF?: T;
        effectiveFrom?: T;
        id?: T;
      };
  paymentMethods?: T;
  contactForEnquiries?:
    | T
    | {
        name?: T;
        phone?: T;
        email?: T;
      };
  lastApprovedDate?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vip-lounge_select".
 */
export interface VipLoungeSelect<T extends boolean = true> {
  pageTitle?: T;
  introduction?: T;
  amenities?:
    | T
    | {
        item?: T;
        id?: T;
      };
  eligibility?: T;
  bookingInformation?: T;
  operatingHours?: T;
  contactPhone?: T;
  contactEmail?: T;
  loungeImages?:
    | T
    | {
        image?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "emergency-services_select".
 */
export interface EmergencyServicesSelect<T extends boolean = true> {
  status?: T;
  pageTitle?: T;
  introduction?: T;
  primaryEmergencyNumber?: T;
  serviceContacts?:
    | T
    | {
        serviceName?: T;
        phone?: T;
        description?: T;
        available24h?: T;
        id?: T;
      };
  medicalFacilities?: T;
  evacuationProcedures?: T;
  lastVerifiedDate?: T;
  verifiedBy?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "working-hours-directions_select".
 */
export interface WorkingHoursDirectionsSelect<T extends boolean = true> {
  pageTitle?: T;
  opHours?:
    | T
    | {
        description?: T;
        schedule?:
          | T
          | {
              dayOrPeriod?: T;
              hours?: T;
              id?: T;
            };
      };
  departmentHours?:
    | T
    | {
        department?: T;
        hours?: T;
        notes?: T;
        id?: T;
      };
  location?:
    | T
    | {
        address?: T;
        googleMapsURL?: T;
        mapEmbedURL?: T;
        coordinates?:
          | T
          | {
              latitude?: T;
              longitude?: T;
            };
      };
  gettingHere?:
    | T
    | {
        transportMode?: T;
        description?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "useful-links_select".
 */
export interface UsefulLinksSelect<T extends boolean = true> {
  pageTitle?: T;
  introduction?: T;
  linkGroups?:
    | T
    | {
        groupName?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              description?: T;
              openInNewTab?: T;
              id?: T;
            };
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "management-staff_select".
 */
export interface ManagementStaffSelect<T extends boolean = true> {
  pageTitle?: T;
  introduction?: T;
  managementTeam?:
    | T
    | {
        name?: T;
        title?: T;
        photo?: T;
        bio?: T;
        department?: T;
        displayOrder?: T;
        isVisible?: T;
        id?: T;
      };
  departments?:
    | T
    | {
        departmentName?: T;
        description?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages_select".
 */
export interface LegalPagesSelect<T extends boolean = true> {
  disclaimer?:
    | T
    | {
        title?: T;
        content?: T;
        lastUpdated?: T;
      };
  termsOfUse?:
    | T
    | {
        title?: T;
        content?: T;
        lastUpdated?: T;
        effectiveDate?: T;
      };
  privacyPolicy?:
    | T
    | {
        title?: T;
        content?: T;
        lastUpdated?: T;
        dataControllerName?: T;
        dataControllerEmail?: T;
      };
  cookiePolicy?:
    | T
    | {
        title?: T;
        content?: T;
        lastUpdated?: T;
      };
  approvalNotes?: T;
  approvalHistory?:
    | T
    | {
        approvedBy?: T;
        approvedAt?: T;
        notes?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}